# Generated by Django 5.0.6 on 2024-07-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='expire_at',
        ),
    ]
