# Generated by Django 5.0.6 on 2024-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_tweet_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='club_name',
            field=models.CharField(default='General Club', max_length=40),
            preserve_default=False,
        ),
    ]
